const traducoes = {
  pt: {
    'nav-sobre':        'sobre',
    'nav-skills':       'skills',
    'nav-interesses':   'interesses',
    'nav-contato':      'contato',
    'hero-tag':         'disponível para projetos',
    'hero-titulo':      'Oi, eu sou<br>o <span>Pedro</span> 👋',
    'hero-desc':        'Entusiasta de tecnologia, desenvolvedor web e apaixonado por automação. Construindo coisas legais com código.',
    'btn-contato':      'entrar em contato',
    'btn-skills':       'ver skills →',
    'label-habilidades':'habilidades',
    'titulo-skills':    'O que eu sei fazer',
    'chip-automacao':   'Automação',
    'chip-robotica':    'Robótica (LEGO)',
    'label-idiomas':    'idiomas',
    'lang-pt':          'Português',
    'lang-pt-nivel':    'Nativo',
    'lang-en':          'Inglês',
    'lang-en-nivel':    'B2 — Intermediário avançado',
    'lang-de':          'Alemão',
    'lang-de-nivel':    'Aprendendo em breve...',
    'label-interesses': 'interesses',
    'titulo-interesses':'O que me move',
    'card-web-p':       'Criar interfaces e sistemas que resolvem problemas reais.',
    'card-auto-h3':     'Automação',
    'card-auto-p':      'Fazer a máquina trabalhar por mim. Tarefas repetitivas? Nunca mais.',
    'card-ia-h3':       'Inteligência Artificial',
    'card-ia-p':        'Explorar o que é possível com IA no mundo real.',
    'card-devops-p':    'Objetivo futuro: dominar pipelines, containers e infra como código.',
    'label-contato':    'contato',
    'titulo-contato':   'Vamos conversar?',
    'footer-texto':     'feito com <span>♥</span> e muito CSS por pedro',
  },
  en: {
    'nav-sobre':        'about',
    'nav-skills':       'skills',
    'nav-interesses':   'interests',
    'nav-contato':      'contact',
    'hero-tag':         'available for projects',
    'hero-titulo':      'Hey, I\'m<br><span>Pedro</span> 👋',
    'hero-desc':        'Tech enthusiast, web developer and automation lover. Building cool things with code.',
    'btn-contato':      'get in touch',
    'btn-skills':       'see skills →',
    'label-habilidades':'skills',
    'titulo-skills':    'What I can do',
    'chip-automacao':   'Automation',
    'chip-robotica':    'Robotics (LEGO)',
    'label-idiomas':    'languages',
    'lang-pt':          'Portuguese',
    'lang-pt-nivel':    'Native',
    'lang-en':          'English',
    'lang-en-nivel':    'B2 — Upper intermediate',
    'lang-de':          'German',
    'lang-de-nivel':    'Learning soon...',
    'label-interesses': 'interests',
    'titulo-interesses':'What drives me',
    'card-web-p':       'Building interfaces and systems that solve real problems.',
    'card-auto-h3':     'Automation',
    'card-auto-p':      'Let the machine do the work. Repetitive tasks? Never again.',
    'card-ia-h3':       'Artificial Intelligence',
    'card-ia-p':        'Exploring what\'s possible with AI in the real world.',
    'card-devops-p':    'Future goal: master pipelines, containers and infrastructure as code.',
    'label-contato':    'contact',
    'titulo-contato':   'Let\'s talk?',
    'footer-texto':     'made with <span>♥</span> and lots of CSS by pedro',
  }
};

const elementos = {
  'nav-sobre':         () => document.querySelector('.nav-links li:nth-child(1) a'),
  'nav-skills':        () => document.querySelector('.nav-links li:nth-child(2) a'),
  'nav-interesses':    () => document.querySelector('.nav-links li:nth-child(3) a'),
  'nav-contato':       () => document.querySelector('.nav-links li:nth-child(4) a'),
  'hero-tag':          () => document.querySelector('.hero-tag'),
  'hero-titulo':       () => document.querySelector('.hero h1'),
  'hero-desc':         () => document.querySelector('.hero-desc'),
  'btn-contato':       () => document.querySelector('.btn-primary'),
  'btn-skills':        () => document.querySelector('.btn-ghost'),
  'label-habilidades': () => document.querySelector('#skills .section-label'),
  'titulo-skills':     () => document.querySelector('#skills h2'),
  'chip-automacao':    () => document.querySelector('.skills-grid .skill-chip:nth-child(5)'),
  'chip-robotica':     () => document.querySelector('.skills-grid .skill-chip:nth-child(6)'),
  'label-idiomas':     () => document.querySelectorAll('#skills .section-label')[1],
  'lang-pt':           () => document.querySelector('.lang-bar-wrap .lang-item:nth-child(1) .lang-name'),
  'lang-pt-nivel':     () => document.querySelector('.lang-bar-wrap .lang-item:nth-child(1) .lang-level'),
  'lang-en':           () => document.querySelector('.lang-bar-wrap .lang-item:nth-child(2) .lang-name'),
  'lang-en-nivel':     () => document.querySelector('.lang-bar-wrap .lang-item:nth-child(2) .lang-level'),
  'lang-de':           () => document.querySelector('.lang-bar-wrap .lang-item:nth-child(3) .lang-name'),
  'lang-de-nivel':     () => document.querySelector('.lang-bar-wrap .lang-item:nth-child(3) .lang-level'),
  'label-interesses':  () => document.querySelector('#interesses .section-label'),
  'titulo-interesses': () => document.querySelector('#interesses h2'),
  'card-web-p':        () => document.querySelector('.interest-card:nth-child(1) p'),
  'card-auto-h3':      () => document.querySelector('.interest-card:nth-child(2) h3'),
  'card-auto-p':       () => document.querySelector('.interest-card:nth-child(2) p'),
  'card-ia-h3':        () => document.querySelector('.interest-card:nth-child(3) h3'),
  'card-ia-p':         () => document.querySelector('.interest-card:nth-child(3) p'),
  'card-devops-p':     () => document.querySelector('.interest-card:nth-child(4) p'),
  'label-contato':     () => document.querySelector('#contato .section-label'),
  'titulo-contato':    () => document.querySelector('#contato h2'),
  'footer-texto':      () => document.querySelector('footer'),
};

let currentLang = 'pt';

function toggleLang() {
  currentLang = currentLang === 'pt' ? 'en' : 'pt';
  document.querySelector('.lang-toggle').textContent = currentLang === 'pt' ? 'EN' : 'PT';
  document.documentElement.lang = currentLang === 'pt' ? 'pt-BR' : 'en';

  for (const chave in elementos) {
    const el = elementos[chave]();
    if (el) el.innerHTML = traducoes[currentLang][chave];
  }
}